<a href="https://colab.research.google.com/github/ANEESAAYAZ/internship_pandas/blob/main/pandas_sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
import pandas as pd

In [89]:
sample=pd.DataFrame({
    "order_id":["01","02","03"],
    "amount":["100","200","300"],
    "customer_id":["c01","c02","c03"]
})

In [90]:
sample

  order_id amount customer_id
0       01    100         c01
1       02    200         c02
2       03    300         c03

In [91]:
print("Index: ",sample.index.to_list(),"\nColumns: ",sample.columns.to_list())

Index:  [0, 1, 2]
Columns:  ['order_id', 'amount', 'customer_id']

In [92]:
orders=pd.read_csv("product_orders.csv",parse_dates=["order_date"])

In [93]:
orders.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status
0,ORD50001,CUST1077,PROD119,2025-01-02,1,29.99,Shipped
1,ORD50002,CUST1076,PROD124,2025-01-02,5,79.99,Delivered
2,ORD50003,CUST1055,PROD134,2025-01-02,2,99.99,Delivered
3,ORD50004,CUST1128,PROD107,2025-01-03,5,14.99,Delivered
4,ORD50005,CUST1179,PROD100,2025-01-05,2,199.99,Cancelled

In [94]:
orders.dtypes

order_id                object
customer_id             object
product_id              object
order_date      datetime64[ns]
quantity                 int64
unit_price             float64
order_status            object
dtype: object

In [95]:
orders.order_id.head()

0    ORD50001
1    ORD50002
2    ORD50003
3    ORD50004
4    ORD50005
Name: order_id, dtype: object

In [96]:
orders.order_id.dtype

dtype('O')

In [97]:
orders[["order_id","quantity","unit_price"]]

     order_id  quantity  unit_price
0    ORD50001         1       29.99
1    ORD50002         5       79.99
2    ORD50003         2       99.99
3    ORD50004         5       14.99
4    ORD50005         2      199.99
..        ...       ...         ...
495  ORD50496         2       29.99
496  ORD50497         1       19.99
497  ORD50498         2       19.99
498  ORD50499         3       29.99
499  ORD50500         1       19.99

[500 rows x 3 columns]

In [98]:
orders.loc[56]

order_id                   ORD50057
customer_id                CUST1015
product_id                  PROD103
order_date      2025-02-11 00:00:00
quantity                          2
unit_price                   149.99
order_status              Delivered
Name: 56, dtype: object

In [99]:
orders.iloc[56:78]

,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status
56,ORD50057,CUST1015,PROD103,2025-02-11,2,149.99,Delivered
57,ORD50058,CUST1098,PROD131,2025-02-14,3,39.99,Shipped
58,ORD50059,CUST1014,PROD124,2025-02-15,4,79.99,Delivered
59,ORD50060,CUST1029,PROD115,2025-02-16,3,99.99,Returned
60,ORD50061,CUST1077,PROD112,2025-02-17,2,149.99,Returned
61,ORD50062,CUST1089,PROD125,2025-02-17,5,19.99,Delivered
62,ORD50063,CUST1047,PROD107,2025-02-17,2,14.99,Returned
63,ORD50064,CUST1128,PROD107,2025-02-18,1,14.99,Delivered
64,ORD50065,CUST1100,PROD134,2025-02-18,5,99.99,Delivered
65,ORD50066,CUST1028,PROD130,2025-02-18,4,39.99,Delivered
66,ORD50067,CUST1165,PROD123,2025-02-19,1,19.99,Delivered
67,ORD50068,CUST1028,PROD130,2025-02-19,2,39.99,Delivered
68,ORD50069,CUST1072,PROD112,2025-02-20,3,149.99,Delivered
69,ORD50070,CUST1035,PROD128,2025-02-20,4,29.99,Delivered
70,ORD50071,CUST1189,PROD108,2025-02-21,3,4.99,Delivered
71,ORD50072,CUST1057,PROD117,2025-02-23,5,99.99,Delivered
72,ORD50073,CUST1174,PROD105,2025-02-24,1,99.99,Processing
73,ORD50074,CUST1193,PROD115,2025-02-25,5,99.99,Returned
74,ORD50075,CUST1044,PROD113,2025-02-25,2,4.99,Delivered
75,ORD50076,CUST1006,PROD116,2025-02-25,1,9.99,Delivered
76,ORD50077,CUST1003,PROD119,2025-02-26,1,29.99,Delivered
77,ORD50078,CUST1037,PROD101,2025-02-27,2,49.99,Delivered

In [100]:
orders=orders.reset_index()
orders

,index,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status
0,0,ORD50001,CUST1077,PROD119,2025-01-02,1,29.99,Shipped
1,1,ORD50002,CUST1076,PROD124,2025-01-02,5,79.99,Delivered
2,2,ORD50003,CUST1055,PROD134,2025-01-02,2,99.99,Delivered
3,3,ORD50004,CUST1128,PROD107,2025-01-03,5,14.99,Delivered
4,4,ORD50005,CUST1179,PROD100,2025-01-05,2,199.99,Cancelled
...,...,...,...,...,...,...,...,...
495,495,ORD50496,CUST1081,PROD127,2025-12-25,2,29.99,Delivered
496,496,ORD50497,CUST1086,PROD123,2025-12-27,1,19.99,Shipped
497,497,ORD50498,CUST1151,PROD109,2025-12-29,2,19.99,Cancelled
498,498,ORD50499,CUST1174,PROD114,2025-12-29,3,29.99,Delivered
499,499,ORD50500,CUST1082,PROD125,2025-12-31,1,19.99,Delivered

In [101]:
orders.loc[67]

index                            67
order_id                   ORD50068
customer_id                CUST1028
product_id                  PROD130
order_date      2025-02-19 00:00:00
quantity                          2
unit_price                    39.99
order_status              Delivered
Name: 67, dtype: object

In [102]:
orders.iloc[67:98]

,index,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status
67,67,ORD50068,CUST1028,PROD130,2025-02-19,2,39.99,Delivered
68,68,ORD50069,CUST1072,PROD112,2025-02-20,3,149.99,Delivered
69,69,ORD50070,CUST1035,PROD128,2025-02-20,4,29.99,Delivered
70,70,ORD50071,CUST1189,PROD108,2025-02-21,3,4.99,Delivered
71,71,ORD50072,CUST1057,PROD117,2025-02-23,5,99.99,Delivered
72,72,ORD50073,CUST1174,PROD105,2025-02-24,1,99.99,Processing
73,73,ORD50074,CUST1193,PROD115,2025-02-25,5,99.99,Returned
74,74,ORD50075,CUST1044,PROD113,2025-02-25,2,4.99,Delivered
75,75,ORD50076,CUST1006,PROD116,2025-02-25,1,9.99,Delivered
76,76,ORD50077,CUST1003,PROD119,2025-02-26,1,29.99,Delivered
77,77,ORD50078,CUST1037,PROD101,2025-02-27,2,49.99,Delivered
78,78,ORD50079,CUST1081,PROD113,2025-02-28,1,4.99,Returned
79,79,ORD50080,CUST1034,PROD133,2025-02-28,5,199.99,Delivered
80,80,ORD50081,CUST1192,PROD117,2025-03-01,2,99.99,Cancelled
81,81,ORD50082,CUST1095,PROD121,2025-03-01,5,19.99,Shipped
82,82,ORD50083,CUST1170,PROD104,2025-03-01,3,39.99,Delivered
83,83,ORD50084,CUST1004,PROD115,2025-03-02,1,99.99,Processing
84,84,ORD50085,CUST1027,PROD138,2025-03-02,2,24.99,Delivered
85,85,ORD50086,CUST1092,PROD121,2025-03-03,5,19.99,Cancelled
86,86,ORD50087,CUST1033,PROD100,2025-03-04,3,199.99,Delivered
87,87,ORD50088,CUST1033,PROD128,2025-03-05,2,29.99,Delivered
88,88,ORD50089,CUST1005,PROD130,2025-03-07,3,39.99,Processing
89,89,ORD50090,CUST1054,PROD115,2025-03-07,1,99.99,Delivered
90,90,ORD50091,CUST1153,PROD101,2025-03-09,1,49.99,Delivered
91,91,ORD50092,CUST1159,PROD133,2025-03-09,4,199.99,Delivered
92,92,ORD50093,CUST1102,PROD110,2025-03-10,1,19.99,Delivered
93,93,ORD50094,CUST1037,PROD136,2025-03-11,2,79.99,Delivered
94,94,ORD50095,CUST1090,PROD114,2025-03-12,2,29.99,Shipped
95,95,ORD50096,CUST1124,PROD115,2025-03-12,2,99.99,Cancelled
96,96,ORD50097,CUST1030,PROD131,2025-03-12,1,39.99,Delivered
97,97,ORD50098,CUST1082,PROD105,2025-03-12,2,99.99,Delivered

Filter

In [103]:
completed=orders[orders["order_status"]=="Delivered"]

In [104]:
completed

,index,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status
1,1,ORD50002,CUST1076,PROD124,2025-01-02,5,79.99,Delivered
2,2,ORD50003,CUST1055,PROD134,2025-01-02,2,99.99,Delivered
3,3,ORD50004,CUST1128,PROD107,2025-01-03,5,14.99,Delivered
5,5,ORD50006,CUST1052,PROD117,2025-01-06,1,99.99,Delivered
7,7,ORD50008,CUST1096,PROD135,2025-01-06,3,99.99,Delivered
...,...,...,...,...,...,...,...,...
493,493,ORD50494,CUST1052,PROD102,2025-12-24,2,79.99,Delivered
494,494,ORD50495,CUST1043,PROD105,2025-12-24,1,99.99,Delivered
495,495,ORD50496,CUST1081,PROD127,2025-12-25,2,29.99,Delivered
498,498,ORD50499,CUST1174,PROD114,2025-12-29,3,29.99,Delivered
499,499,ORD50500,CUST1082,PROD125,2025-12-31,1,19.99,Delivered

In [105]:
mix=orders[(orders["order_status"]=="Delivered")&(orders["quantity"]>2)]

In [106]:
mix

,index,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status
1,1,ORD50002,CUST1076,PROD124,2025-01-02,5,79.99,Delivered
3,3,ORD50004,CUST1128,PROD107,2025-01-03,5,14.99,Delivered
7,7,ORD50008,CUST1096,PROD135,2025-01-06,3,99.99,Delivered
16,16,ORD50017,CUST1070,PROD102,2025-01-15,4,79.99,Delivered
17,17,ORD50018,CUST1058,PROD131,2025-01-15,5,39.99,Delivered
...,...,...,...,...,...,...,...,...
472,472,ORD50473,CUST1195,PROD132,2025-12-13,5,39.99,Delivered
482,482,ORD50483,CUST1082,PROD132,2025-12-17,3,39.99,Delivered
484,484,ORD50485,CUST1147,PROD120,2025-12-20,5,99.99,Delivered
490,490,ORD50491,CUST1162,PROD119,2025-12-21,5,29.99,Delivered
498,498,ORD50499,CUST1174,PROD114,2025-12-29,3,29.99,Delivered

In [107]:
orders_with_total=orders.assign(revenue=orders["quantity"] * orders["unit_price"])

In [108]:
orders.head()

,index,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status
0,0,ORD50001,CUST1077,PROD119,2025-01-02,1,29.99,Shipped
1,1,ORD50002,CUST1076,PROD124,2025-01-02,5,79.99,Delivered
2,2,ORD50003,CUST1055,PROD134,2025-01-02,2,99.99,Delivered
3,3,ORD50004,CUST1128,PROD107,2025-01-03,5,14.99,Delivered
4,4,ORD50005,CUST1179,PROD100,2025-01-05,2,199.99,Cancelled

In [109]:
orders_with_total

,index,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status,revenue
0,0,ORD50001,CUST1077,PROD119,2025-01-02,1,29.99,Shipped,29.99
1,1,ORD50002,CUST1076,PROD124,2025-01-02,5,79.99,Delivered,399.95
2,2,ORD50003,CUST1055,PROD134,2025-01-02,2,99.99,Delivered,199.98
3,3,ORD50004,CUST1128,PROD107,2025-01-03,5,14.99,Delivered,74.95
4,4,ORD50005,CUST1179,PROD100,2025-01-05,2,199.99,Cancelled,399.98
...,...,...,...,...,...,...,...,...,...
495,495,ORD50496,CUST1081,PROD127,2025-12-25,2,29.99,Delivered,59.98
496,496,ORD50497,CUST1086,PROD123,2025-12-27,1,19.99,Shipped,19.99
497,497,ORD50498,CUST1151,PROD109,2025-12-29,2,19.99,Cancelled,39.98
498,498,ORD50499,CUST1174,PROD114,2025-12-29,3,29.99,Delivered,89.97
499,499,ORD50500,CUST1082,PROD125,2025-12-31,1,19.99,Delivered,19.99

Sorting

In [110]:
orders_with_total.sort_values(by="revenue",ascending=False).head()

,index,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status,revenue
463,463,ORD50464,CUST1133,PROD133,2025-12-03,5,199.99,Delivered,999.95
243,243,ORD50244,CUST1152,PROD133,2025-07-07,5,199.99,Shipped,999.95
344,344,ORD50345,CUST1150,PROD100,2025-09-15,5,199.99,Delivered,999.95
132,132,ORD50133,CUST1137,PROD133,2025-04-07,5,199.99,Delivered,999.95
79,79,ORD50080,CUST1034,PROD133,2025-02-28,5,199.99,Delivered,999.95

Group By

In [111]:
products=pd.read_csv("products.csv")

In [112]:
products.head()

  product_id           category sub_category  unit_cost
0    PROD100        Electronics   Headphones     114.94
1    PROD101             Beauty       Makeup      20.50
2    PROD102           Clothing   Men's Tops      57.98
3    PROD103             Beauty     Skincare      66.81
4    PROD104  Sports & Outdoors         Yoga      24.70

In [113]:
enriched=orders_with_total.merge(products,on="product_id")

In [114]:
enriched.head()

,index,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status,revenue,category,sub_category,unit_cost
0,0,ORD50001,CUST1077,PROD119,2025-01-02,1,29.99,Shipped,29.99,Beauty,Fragrance,14.28
1,1,ORD50002,CUST1076,PROD124,2025-01-02,5,79.99,Delivered,399.95,Home & Kitchen,Cookware,59.89
2,2,ORD50003,CUST1055,PROD134,2025-01-02,2,99.99,Delivered,199.98,Books & Stationery,Art Supplies,40.94
3,3,ORD50004,CUST1128,PROD107,2025-01-03,5,14.99,Delivered,74.95,Books & Stationery,Notebooks,10.13
4,4,ORD50005,CUST1179,PROD100,2025-01-05,2,199.99,Cancelled,399.98,Electronics,Headphones,114.94

In [115]:
revenue_by_category=enriched.groupby("category")["revenue"].sum()

In [116]:
revenue_by_category

category
Beauty                10578.19
Books & Stationery    31256.64
Clothing              15382.60
Electronics            6648.42
Home & Kitchen        10773.57
Sports & Outdoors      8243.44
Name: revenue, dtype: float64

In [117]:
category_count=enriched.groupby("category")["revenue"].count()

In [118]:
category_count

category
Beauty                 67
Books & Stationery    145
Clothing               99
Electronics            59
Home & Kitchen         62
Sports & Outdoors      68
Name: revenue, dtype: int64

In [119]:
multi_agg=enriched.groupby("category").agg(
    revenue_sum=("revenue","sum"),
    revenue_mean=("revenue","mean"),
    order_count=("revenue","count")
)

In [120]:
multi_agg

                    revenue_sum  revenue_mean  order_count
category
Beauty                 10578.19    157.883433           67
Books & Stationery     31256.64    215.563034          145
Clothing               15382.60    155.379798           99
Electronics             6648.42    112.685085           59
Home & Kitchen         10773.57    173.767258           62
Sports & Outdoors       8243.44    121.227059           68

In [123]:
customers=pd.read_csv("customers (1).csv")

In [124]:
customers.head()

,customer_id,first_name,last_name,gender,age,email,city,country,signup_date,acquisition_channel,is_newsletter_subscriber
0,CUST1001,Faisal,Rahman,Male,50,faisal.rahman1001@example.com,Jeddah,Saudi Arabia,2023-11-23,Paid Ads,0
1,CUST1002,Khalid,Hussain,Male,42,khalid.hussain1002@example.com,Kuwait City,Kuwait,2025-05-20,Organic Search,0
2,CUST1003,Chloe,Qureshi,Female,43,chloe.qureshi1003@example.com,Muscat,Oman,2024-08-22,Organic Search,1
3,CUST1004,Lucas,Ali,Male,36,lucas.ali1004@example.com,Sharjah,UAE,2024-04-30,Social Media,1
4,CUST1005,Layla,Saleh,Female,49,layla.saleh1005@example.com,Jeddah,Saudi Arabia,2024-01-07,Social Media,1

In [125]:
full=orders_with_total.merge(customers,on="customer_id",how="left").merge(products,on="product_id",how="left")

In [126]:
full.head()

,index,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status,revenue,first_name,...,age,email,city,country,signup_date,acquisition_channel,is_newsletter_subscriber,category,sub_category,unit_cost
0,0,ORD50001,CUST1077,PROD119,2025-01-02,1,29.99,Shipped,29.99,Arjun,...,35,arjun.qureshi1077@example.com,Dubai,UAE,2022-10-12,Organic Search,1,Beauty,Fragrance,14.28
1,1,ORD50002,CUST1076,PROD124,2025-01-02,5,79.99,Delivered,399.95,Lucas,...,37,lucas.hassan1076@example.com,Doha,Qatar,2024-08-14,Organic Search,1,Home & Kitchen,Cookware,59.89
2,2,ORD50003,CUST1055,PROD134,2025-01-02,2,99.99,Delivered,199.98,Zainab,...,35,zainab.sharma1055@example.com,Dubai,UAE,2023-04-12,Organic Search,1,Books & Stationery,Art Supplies,40.94
3,3,ORD50004,CUST1128,PROD107,2025-01-03,5,14.99,Delivered,74.95,Hassan,...,37,hassan.hassan1128@example.com,Dubai,UAE,2024-12-26,Organic Search,0,Books & Stationery,Notebooks,10.13
4,4,ORD50005,CUST1179,PROD100,2025-01-05,2,199.99,Cancelled,399.98,Hassan,...,18,hassan.patel1179@example.com,Ajman,UAE,2024-12-17,Email,0,Electronics,Headphones,114.94

Date operations

In [127]:
full["order_month"]=full["order_date"].dt.month

In [128]:
full["order_quarter"]=full["order_date"].dt.quarter

In [129]:
full.head()

,index,order_id,customer_id,product_id,order_date,quantity,unit_price,order_status,revenue,first_name,...,city,country,signup_date,acquisition_channel,is_newsletter_subscriber,category,sub_category,unit_cost,order_month,order_quarter
0,0,ORD50001,CUST1077,PROD119,2025-01-02,1,29.99,Shipped,29.99,Arjun,...,Dubai,UAE,2022-10-12,Organic Search,1,Beauty,Fragrance,14.28,1,1
1,1,ORD50002,CUST1076,PROD124,2025-01-02,5,79.99,Delivered,399.95,Lucas,...,Doha,Qatar,2024-08-14,Organic Search,1,Home & Kitchen,Cookware,59.89,1,1
2,2,ORD50003,CUST1055,PROD134,2025-01-02,2,99.99,Delivered,199.98,Zainab,...,Dubai,UAE,2023-04-12,Organic Search,1,Books & Stationery,Art Supplies,40.94,1,1
3,3,ORD50004,CUST1128,PROD107,2025-01-03,5,14.99,Delivered,74.95,Hassan,...,Dubai,UAE,2024-12-26,Organic Search,0,Books & Stationery,Notebooks,10.13,1,1
4,4,ORD50005,CUST1179,PROD100,2025-01-05,2,199.99,Cancelled,399.98,Hassan,...,Ajman,UAE,2024-12-17,Email,0,Electronics,Headphones,114.94,1,1

In [131]:
full["order_quarter"].value_counts()

order_quarter
4    133
3    130
1    124
2    113
Name: count, dtype: int64

In [132]:
monthly_revenue=full.groupby(["order_month","order_quarter"])["revenue"].sum()

In [133]:
monthly_revenue

order_month  order_quarter
1            1                5869.08
2            1                8363.83
3            1                5949.06
4            2                6389.10
5            2                6089.11
6            2                5399.12
7            3                9219.07
8            3                6858.63
9            3                5684.06
10           4                8208.95
11           4                8358.76
12           4                6494.09
Name: revenue, dtype: float64

In [135]:
full.groupby(["order_month"])["revenue"].sum().sort_values(ascending=False)

order_month
7     9219.07
2     8363.83
11    8358.76
10    8208.95
8     6858.63
12    6494.09
4     6389.10
5     6089.11
3     5949.06
1     5869.08
9     5684.06
6     5399.12
Name: revenue, dtype: float64

In [136]:
country_category=full.pivot_table(index="country",columns="category",values="revenue",aggfunc="sum")

In [137]:
country_category

category,Beauty,Books & Stationery,Clothing,Electronics,Home & Kitchen,Sports & Outdoors
country,,,,,,
Bahrain,49.99,499.94,919.93,449.86,59.98,719.90
Kuwait,199.95,1614.90,179.94,NaN,269.93,539.92
Oman,1649.68,2774.74,2749.59,199.94,564.93,674.85
Qatar,949.84,1119.87,1779.81,419.86,1759.83,139.93
Saudi Arabia,1979.67,6979.29,1729.68,539.73,1949.61,2344.64
UAE,5749.06,18267.90,8023.65,5039.03,6169.29,3824.20

In [138]:
full.to_csv("full.csv")